version: '3.8'
services:
  server:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: ts-node src/index.ts
  client:
    build: ../flappy-bird-phaser
    ports:
      - "4000:4000"
    env_file:
      - .env
    command: node_modules/.bin/webpack serve --mode production
