version: '3.8'
services:
  app:
    container_name: flappy-bird-server-dev
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      CORS_ENABLED: ${CORS_ENABLED}
      CORS_ORIGIN: ${CORS_ORIGIN}
      NGROK_ENABLED: ${NGROK_ENABLED}
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
      NGROK_DOMAIN: ${NGROK_DOMAIN}
      NETWORK: ${NETWORK}
      MNEMONIC: ${MNEMONIC}
      PINATA_API_KEY: ${PINATA_API_KEY}
      PINATA_SECRET: ${PINATA_SECRET}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      JETTON_ADDRESS: ${JETTON_ADDRESS}
      FIRST_TIME_SBT_COLLECTION_ADDRESS: ${FIRST_TIME_SBT_COLLECTION_ADDRESS}
      FIVE_TIMES_SBT_COLLECTION_ADDRESS: ${FIVE_TIMES_SBT_COLLECTION_ADDRESS}
    volumes:
      - ./src:/usr/src/app/src
    command: ts-node-dev --respawn src/index.ts
