version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: workspaces/server/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./workspaces/server/src:/app/workspaces/server/src
      # - ./db.sqlite:/app/db.sqlite
    command: npm run dev --workspace=server
    # command: tail -f /dev/null
  client:
    build: ../flappy-bird-phaser
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      # use WATCHPACK_POLLING is needed to fix webpack watch issue on windows
      - WATCHPACK_POLLING=true
    volumes:
      - ../flappy-bird-phaser/src:/app/src
    command: node_modules/.bin/webpack serve --mode development

