version: '3.8'
services:
  server:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./src:/usr/src/app/src
      - ./db.sqlite:/usr/src/app/db.sqlite
    command: ts-node-dev --respawn src/index.ts
  client:
    build: ../flappy-bird-phaser
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      # use WATCHPACK_POLLING is needed to fix webpack watch issue on windows
      - WATCHPACK_POLLING=true
    volumes:
      - ../flappy-bird-phaser/src:/app/src
    command: node_modules/.bin/webpack serve --mode development

